name: deploy-automation

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-releaser
        uses: hackmdio/helm-gh-pages@a3b103e
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          helm_version: 2.16.5
