name: deploy-automation

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-releaser
        uses: hackmdio/helm-gh-pages@bc45b2ad8ea0466f88a031088ad3871f08e761fb
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          helm_version: 2.16.5
